[package]
name = "pgen"
description = "Passphrase Generator"
license = "ISC"
documentation = "https://github.com/yarwelp/pgen/blob/master/README.md"
readme = "README.md"
repository = "https://github.com/yarwelp/pgen"
version = "0.3.0"
authors = ["Erik Nordstrøm <erik@nordstroem.no>"]
homepage = "https://yarwelp.github.io/pgen/"
categories = ["command-line-utilities", "cryptography"]

[dependencies]
rand = "0.4"
clap = {version = "~2.29.1", features = ["yaml"]}
