[workspace]
resolver = "2"

members = ["crates/lexical-data", "crates/pgen", ]

[workspace.dependencies]
rand = "0.8.5"
clap = { version = "4.5.4", default-features = false, features = ["std", "derive", "help", "usage", "error-context"] }
