[package]
name = "pgen"
version = "1.1.0"
authors = ["Erik Nordstrøm <erik@nordstroem.no>"]
edition = "2018"
description = "Passphrase Generator"
license = "ISC"
repository = "https://github.com/ctsrc/Pgen"
categories = ["command-line-utilities", "cryptography"]

[dependencies]
rand = "0.7.2"
clap = { version = "2.33.0", features = ["yaml"] }
