[package]
name = "pgen"
description = "Passphrase Generator"
license = "ISC"
readme = "README.md"
repository = "https://github.com/ctsrc/Pgen/crates/pgen"
version = "2.0.0-alpha.1"
authors = ["Erik Nordstrøm <erik@nordstroem.no>"]
categories = ["command-line-utilities", "cryptography"]
edition = "2021"

[dependencies]
rand = { workspace = true }
clap = { workspace = true }
bip39-lexical-data = { path = "../bip39-lexical-data", version = "1.0.0" }
eff-lexical-data = { path = "../eff-lexical-data", version = "1.0.0" }
